<?php

/**
 * BlogPosts
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Collide MVC
 * @subpackage Model
 * @author     Radu Graur <radu.graur@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class BlogPosts extends BaseBlogPosts
{
    public $log;

    /**
	 * Get all posts
	 *
	 * @access	public
	 * @return	array   all posts
	 */
	public function getAll(){
        $this->log->write( 'BlogPosts::getAll()' );

        $res = Doctrine_Query::create()->
        from( 'BlogPosts' )->
        fetchArray();

		return $res;
    }

    /**
	 * Get all posts
	 *
	 * @access	public
     * @param   integer $id post id
	 * @return	array   one post
	 */
	public function getOne( $id ){
        $this->log->write( 'BlogPosts::getOne(' . $id . ')' );

        $res = Doctrine_Query::create()->
        from( 'BlogPosts' )->
        where( 'id = ?', array( $id ) )->
        fetchArray();

        if( !isset( $res[0] ) ){
            return false;
        }

		return $res[0];
    }

    /**
	 * Add post
	 *
	 * @access	public
     * @param   array   $post   post info to insert
	 * @return	boolean
	 */
	public function add( $post ){
        $this->log->write( 'BlogPosts::add( $post )' );

        $this->title    = $post['title'];
        $this->content  = $post['content'];

        return $this->save();
    }

    /**
	 * Edit post
	 *
	 * @access	public
     * @param   array   $post   post info to edit
	 * @return	boolean
	 */
	public function edit( $post ){
        $this->log->write( 'BlogPosts::edit( $post )' );
        
        return Doctrine_Query::create()->
            update( 'BlogPosts' )->
            set( 'title', '?', $post['title'] )->
            set( 'content', '?', $post['content'] )->
            where( 'id = ?', $post['id'] )->
            execute();
    }

    /**
	 * Delete post
     *
	 * @access	public
     * @param   array   $id post info to delete
	 * @return	boolean
	 */
	public function delete( $id ){
        $this->log->write( 'BlogPosts::delete( ' . $id . ' )' );

        return Doctrine_Query::create()->
            delete( 'BlogPosts' )->
            where( 'id = ?', $id );
    }
}