<?php if( !defined( 'ROOT_PATH' ) ) die( '403: Forbidden' );

/******************************************************************************
 *                                                                            *
 * Collide PHP Framework                                                      *
 *                                                                            *
 * MVC framework for PHP.                                                     *
 *                                                                            *
 * @package     Collide MVC App                                               *
 * @author      Collide Applications Development Team                         *
 * @copyright   Copyright (c) 2009, Collide Applications                      *
 * @license     http://mvc.collide-applications.com/license.txt               *
 * @link        http://mvc.collide-applications.com                           *
 * @since       Version 0.1                                                   *
 *                                                                            *
 ******************************************************************************/

/**
 * BlogPosts
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Collide MVC
 * @subpackage Model
 */
class BlogPosts extends BaseBlogPosts
{
    /**
     * Get all posts
     *
     * @access  public
     * @return  array   all posts
     */
    public function getAll(){
        logWrite( 'BlogPosts::getAll()' );

        return Doctrine_Query::create()->
        from( 'BlogPosts' )->
        orderBy( 'id DESC' )->
        fetchArray();
    }

    /**
     * Get one post
     *
     * @access  public
     * @param   integer $id post id
     * @return  mixed   one post or false if no post founded
     */
    public function getOne( $id ){
        logWrite( 'BlogPosts::getOne(' . $id . ')' );

        $res = Doctrine_Query::create()->
        from( 'BlogPosts' )->
        where( 'id = ?', $id )->
        fetchArray();

        // if no post founded return false
        if( count( $res ) == 0 ){
            return false;
        }

        return $res[0];
    }

    /**
     * Add post
     *
     * @access  public
     * @param   array   $post   post info to insert
     * @return  boolean
     */
    public function add( $post ){
        logWrite( 'BlogPosts::add( $post )' );

        $this->title    = $post['title'];
        $this->content  = $post['content'];

        return $this->save();
    }

    /**
     * Edit post
     *
     * @access  public
     * @param   array   $post   post info to edit
     * @return  boolean
     */
    public function edit( $post ){
        logWrite( 'BlogPosts::edit( $post )' );
        
        return Doctrine_Query::create()->
            update( 'BlogPosts' )->
            set( 'title', '?', $post['title'] )->
            set( 'content', '?', $post['content'] )->
            where( 'id = ?', $post['id'] )->
            execute();
    }

    /**
     * Delete post
     *
     * @access  public
     * @param   integer $id post id to delete
     * @return  boolean
     */
    public function delete( $id ){
        logWrite( 'BlogPosts::delete( ' . $id . ' )' );

        return Doctrine_Query::create()->
            delete( 'BlogPosts' )->
            where( 'id = ?', $id )->
            execute();
    }
}