<?php

/**
 * CName
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CName extends BaseCName
{
    public $log;

	/**
	 * Constructor
     *
     * Set framework name
	 *
	 * @access	public
     * @param   string  $name   framework name
     * @return  void
	 */
	public function __construct(){
		parent::__construct();

//        $this->log->write( 'NameModel::__construct(' . $name . ')' );
	}

	/**
	 * Return framework name
	 *
	 * @access	public
	 * @return	string	framework name
	 */
	public function getName(){
        $this->log->write( 'NameModel::getName()' );

        $query = new Doctrine_Query();
        $res = $query->
        from( 'CName n' )->
        where( 'id', 1 )->
        fetchOne();
        
        return ucfirst( $res->name );
	}
}