<?php

/**
 * CVersion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CVersion extends BaseCVersion
{
    public $log;

	/**
	 * Return framework version
	 *
	 * @access	public
	 * @return	string	framework version
	 */
	public function getVersion(){
        $this->log->write( 'CVersion::getVersion()' );

        $res = Doctrine_Query::create()->
        select( 'version' )->
        from( 'CVersion' )->
        where( 'id', 1 )->
        fetchOne();

		return $res->version;
	}
}