<?php

/**
 * CWelcome
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CWelcome extends BaseCWelcome
{
    public $log;

	/**
	 * Return page title
	 *
	 * @access	public
	 * @return	string	page title
	 */
	public function getTitle(){
        $this->log->write( 'CWelcome::getTitle()' );

        $res = Doctrine_Query::create()->
        select( 'title' )->
        from( 'CWelcome' )->
        where( 'id', 1 )->
        fetchOne();

		return $res->title;
	}

    /**
	 * Return page left panel
	 *
	 * @access	public
	 * @return	string	page left panel
	 */
	public function getLeftPanel(){
        $this->log->write( 'CWelcome::getLeftPanel()' );

        $res = Doctrine_Query::create()->
        select( 'left' )->
        from( 'CWelcome' )->
        where( 'id', 1 )->
        fetchOne();

		return $res->left;
	}

    /**
	 * Return page content
	 *
	 * @access	public
     * @param   string  $name       framework name
     * @param   string  $version    framework version
	 * @return	string	page content
	 */
	public function getContent( $name, $version ){
        $this->log->write( 'CWelcome::getContent()' );

        $res = Doctrine_Query::create()->
        select( 'content' )->
        from( 'CWelcome' )->
        where( 'id', 1 )->
        fetchOne();

		return sprintf( $res->content, $name, $version );
	}
}